clear all;
close all;

Fig=figure('Name','Lupu Miruna Proiect GAC',... 
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8],...
           'NumberTitle','off');
       
x = imread('coperta.jpg');
image(x);
set(gca,'Position',[0 0 1 1]);
axis off;

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.32 0.8 0.33 0.11],...
          'String','Filtru trece jos si Filtru trece sus in RC',...
          'backgroundcolor','#C8E8EE',...
          'Foregroundcolor','black',...
          'FontWeight','bold',...
          'Fontname','TIMES NEW ROMAN',...
          'FontSize',22);
      
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.04 0.2 0.2 0.11],...
          'string',' Proiect ',...
          'FontName','TIMES NEW ROMAN',...
          'FontSize',15,...
          'Backgroundcolor','#74A1A9',...
          'Foregroundcolor','#EAF8FB',...
          'Callback','filtre');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.4 0.2 0.2 0.11],...
          'string',' Prezentare PPT ',...
          'FontName','TIMES NEW ROMAN',...
          'FontSize',15,...
          'Backgroundcolor','#74A1A9',...
          'Foregroundcolor','#EAF8FB',...
          'Callback','open (''prezentare.pptx'')');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.77 0.2 0.2 0.11],...
          'string',' Documentatie ',...
          'FontName','TIMES NEW ROMAN',...
          'FontSize',15,...
          'Backgroundcolor','#74A1A9',...
          'Foregroundcolor','#EAF8FB',...
          'Callback','open (''Documentatie.docx'')');


uicontrol('Style', 'pushbutton', ...
          'Units', 'normalized',...
          'Position', [0.45 0.01 0.1 0.05],...
          'Fontname', 'Times New Roman',...
          'FontWeight','bold',...
          'FontSize',10,...
          'FontAngle', 'italic',...
          'Backgroundcolor','#A50505',...
          'Foregroundcolor','#EAF8FB',...
          'string' ,'EXIT',...
          'Callback', 'close'); 

f= uimenu('Label','Documentatie');
   uimenu(f,'Label','Prima Pagina','Callback','coperta');
   uimenu(f,'Label','Ghid de prezentare','Callback','open(''prezentare.pptx'')');
   uimenu(f,'Label','Ecuatii','Callback','open(''Documentatie.docx'')');
   uimenu(f,'Label','Iesire','Callback','close',...
                    'Separator','on','Accelerator','Q');