function FTS(R, C, min, max, A)

Fig=figure('Name','Lupu Miruna Proiect GAC',... 
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8],...
           'NumberTitle','off',...
           'Color','#B0CFD9');

%------Chenar unde introducem datele de intare----

uibuttongroup('Visible','on',...
              'BackgroundColor','#D6F5FF',...
              'Title','Datele de intrare','Fontangle','italic',...
              'FontSize',10,...
              'Fontname', 'Times new roman',...
              'TitlePosition','centertop',...
              'Tag','radiobutton',...
              'Position',[0.009 0.68 0.22 0.3]);
%-----------Date de intrare---------------

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.03 0.87 0.13 .03],...
          'HorizontalAlignment', 'left',...
          'Fontname', 'Times new roman',...
          'BackgroundColor','#D6F5FF',...
          'Foregroundcolor','#4B3B3B',...
          'FontSize',13,...
          'String','Rezistența [Ω]: ');

uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.12 0.87 0.09 .03],...
          'BackgroundColor','#D6F5FF',...
          'FontSize',13,...
          'ForegroundColor','k',...
          'String',R,...
          'Callback','R=str2num(get(gco,''String''));close;FTS(R, C, min, max, A);');
%-------------------------------------

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.03 0.82 0.13 .03],...
          'HorizontalAlignment', 'left',...
          'Fontname', 'Times new roman',...
          'BackgroundColor','#D6F5FF',...
          'Foregroundcolor','#4B3B3B',...
          'FontSize',13,...
          'String','Capacitate [F]: ');

uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.12 0.82 0.09 .03],...
          'BackgroundColor','#D6F5FF',...
          'FontSize',13,...
          'ForegroundColor','k',...
          'String',C,...
          'Callback','C = str2num(get(gco,''String''));close;FTS(R, C, min, max, A);');

%--------Chenar cu rezultatul calculelor--------------

uibuttongroup('Visible','on',...
              'BackgroundColor','#D6F5FF',...
              'Title','Calcule','Fontangle','italic',...
              'FontSize',10,...
              'Fontname', 'Times new roman',...
              'TitlePosition','centertop',...
              'Tag','radiobutton',...
              'Position',[0.23 0.68 0.22 0.3]);

%----------Buton back------------

uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Position',[0.01 0.01 0.1 0.05],... 
          'FontName','Times New Roman',...
          'FontSize',15,...
          'FontWeight','bold',...
          'foregroundcolor','black',... 
          'String','Back',...
          'Callback','filtre');

%------Circuit: Filtru-trece-sus-------

ho = axes( 'Units','Normalized', ...
           'Position',[0.01 0.1 0.4 0.4]);
uistack(ho,'bottom');
V=imread('fts.jpg');
hp = imagesc(V);
colormap gray

set(ho,'handlevisibility','off', ...
       'visible','off');
set(hp,'alphadata',1);

%------Buton de exit--------

uicontrol('Style', 'pushbutton', ...
          'Units', 'normalized',...
          'Position', [0.88 0.01 0.1 0.05],...
          'Fontname', 'Times New Roman',...
          'FontWeight','bold',...
          'FontSize',10,...
          'FontAngle', 'italic',...
          'Backgroundcolor','#A50505',...
          'Foregroundcolor','#EAF8FB',...
          'string' ,'EXIT',...
          'Callback', 'close');

%----Calcule-------------------

w0=1/(R*C);
f0=1/(2*pi*R*C);

uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.3 0.87 0.09 .03],...
          'FontSize',13,...
          'HorizontalAlignment', 'left',...
          'Fontname', 'Times new roman',...
          'BackgroundColor','#D6F5FF',...
          'Foregroundcolor','#4B3B3B',...
          'FontWeight','b',...
          'String',['w0 = ',num2str(fix(w0)),' rad/s ']); 

uicontrol('Style','Text',...
          'Units','Normalized',...
          'Position',[0.294 0.82 0.09 .03],...
          'FontSize',13,...
          'Fontname', 'Times new roman',...
          'BackgroundColor','#D6F5FF',...
          'Foregroundcolor','#4B3B3B',...
          'FontWeight','b',...
          'String',[' f0 = ',num2str(fix(f0)),' Hz ']);


%----Formulele in j pentru FTS----

w = logspace(min,max,100);     %Valoare omega
f = w./(2*pi);                 %Valoarea frecventei                 
sus = 1j*w;
jos = w0 + 1j*w;
H = abs(sus./jos);             %Functia de transfer
gain = 20*log10(H);            %Calculul cresterii
phase=180/pi*angle(sus./jos);  %Calculul fazei semnalului in grade
%phase=pi/2-(w/w0);            %Calculul fazei semnalului in radiani
%phase=atan(f0);

%-------------------------------------
uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.03 0.77 0.13 .03],...
          'HorizontalAlignment', 'left',...
          'Fontname', 'Times new roman',...
          'BackgroundColor','#D6F5FF',...
          'Foregroundcolor','#4B3B3B',...
          'FontSize',13,...
          'String','Min: ');

uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.12 0.77 0.09 .03],...
          'BackgroundColor','#D6F5FF',...
          'FontSize',13,...
          'ForegroundColor','k',...
          'String',min,...
          'Callback','Min=str2num(get(gco,''String''));close;FTS(R, C, min, max, A);');

%-------------------------------------

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.03 0.72 0.13 .03],...
          'HorizontalAlignment', 'left',...
          'Fontname', 'Times new roman',...
          'BackgroundColor','#D6F5FF',...
          'Foregroundcolor','#4B3B3B',...
          'FontSize',13,...
          'String','Max: ');

uicontrol('Style','Edit',...
          'Units','Normalized',...
          'Position',[0.12 0.72 0.09 .03],...
          'BackgroundColor','#D6F5FF',...
          'FontSize',13,...
          'ForegroundColor','k',...
          'String',max,...
          'Callback','Max = str2num(get(gco,''String''));close;FTS(R, C, min, max, A);');



%------Caracteristica de frecventa la scara dublu logaritmica-----

subplot('Position',[0.49 0.42 0.5 0.23]);
semilogx(f, gain,'r','LineWidth',1.5);
grid on;
title('Caracteristica de frecventa la scara dublu logaritmica','fontname','Times New Roman');
xlabel('Frecventa [Hz]','fontweight', 'bold', 'fontname', 'Times New Roman','color','#5B6366','fontsize',10);
ylabel('Castigul [dB] ','fontweight', 'bold', 'fontname', 'Times New Roman','color','#5B6366','fontsize',12);

%-------Caracteristica de faza la scara semilogaritmica-------

subplot('Position',[0.49 0.1 0.5 0.23]);
semilogx(f,phase, 'c','LineWidth',1.5);
grid on;
title('Caracteristica de faza la scara semilogaritmica','fontname','Times New Roman');
xlabel('Frecventa [Hz]','fontweight', 'bold', 'fontname', 'Times New Roman','color','#5B6366','fontsize',10);
ylabel('Faza\phi [°C]','fontweight', 'bold', 'fontname', 'Times New Roman','color','#5B6366','fontsize',12);

%-------Caracteristica de transfer-------

subplot('Position', [0.49 0.74 0.5 0.23]);
semilogx(f,H,'m--','LineWidth',1.5);
grid on; 
title('Caracteristica de transfer','fontname','Times New Roman');
xlabel('Frecventa [ Hz ]','fontweight','bold', 'fontname', 'Times New Roman','color','#5B6366','fontsize',10);
ylabel('Functia de transfer [V] ','fontweight','bold', 'fontname', 'Times New Roman','color','#5B6366','fontsize',12);    
%----------------------------------------
f= uimenu('Label','Documentatie');
   uimenu(f,'Label','Prima Pagina','Callback','coperta');
   uimenu(f,'Label','Ghid de prezentare','Callback','open(''prezentare.pptx'')');
   uimenu(f,'Label','Ecuatii','Callback','open(''Documentatie.docx'')');
   uimenu(f,'Label','Iesire','Callback','close',...
                    'Separator','on','Accelerator','Q');
end